"""Trusted stage execution profiles for Claude worker sessions.

Profiles are generated by the coordinator from trusted policy for every run. Nothing in
a Jira comment, the application's CLAUDE.md or generated code can widen them. Layers:

1. ``--restricted``: user/project/local settings are ignored (no inherited hooks,
   plugins or MCP servers), file tools are confined to the working directories, and
   bypassPermissions is refused.
2. ``--tools``: only the tools the role needs exist in the session.
3. ``permissions`` in a generated ``--settings`` file with ``dontAsk``: anything not
   explicitly allowed is denied; deny rules always win.
4. OS sandbox for Bash (Seatbelt on macOS, bubblewrap on Linux): filesystem writes
   limited to the run's directories, credential directories unreadable, network
   limited to an allowlist, no unsandboxed escape hatch, hard failure if unavailable.

These layers are a boundary for an honest-but-fallible agent working on a trusted
repository. Tests execute repository code, so review/verification of an untrusted
repository is not a complete security boundary; doctor reports what it verified.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any


class Role(StrEnum):
    AUTHOR = "author"  # refine, plan: write documents to the output dir
    IMPLEMENTER = "implementer"  # implement: edit the feature worktree, run tests
    REVIEWER = "reviewer"  # review: read-only code access, report to output dir
    VERIFIER = "verifier"  # verify: run commands in a disposable worktree
    RESOLVER = "resolver"  # resolve-blocker: the implementer, plus asking the developer questions


PROCEDURE_ROLES: dict[str, Role] = {
    "refine-ticket": Role.AUTHOR,
    "plan-ticket": Role.AUTHOR,
    "implement-ticket": Role.IMPLEMENTER,
    "review-ticket": Role.REVIEWER,
    "verify-ticket": Role.VERIFIER,
    "resolve-conflicts": Role.IMPLEMENTER,
    "investigate-ticket": Role.VERIFIER,
    "resolve-blocker": Role.RESOLVER,
}

# Paths in the application worktree that an implementation must never change.
PROTECTED_WORKTREE_PATHS = (
    ".github/**",
    "docs/delivery/**",
    ".claude/**",
    "CLAUDE.md",
    ".mcp.json",
)

# Home-relative credential and configuration locations unreadable from Bash.
CREDENTIAL_PATHS = (
    "~/.ssh",
    "~/.config/gh",
    "~/.aws",
    "~/.azure",
    "~/.config/gcloud",
    "~/.kube",
    "~/.docker",
    "~/.netrc",
    "~/.git-credentials",
    "~/.npmrc",
    "~/.pypirc",
    "~/.claude",
    "~/.claude.json",
    "~/.config/anthropic",
    "~/Library/Keychains",
)

DENIED_COMMANDS = (
    "gh",
    "git push",
    "git remote",
    "git config",
    "git credential",
    "curl",
    "wget",
    "ssh",
    "scp",
    "sftp",
    "rsync",
    "security",
    "npm publish",
    "npm login",
    "npm adduser",
    "npm token",
    "claude",
)

DEFAULT_NETWORK = {
    Role.AUTHOR: (),
    Role.REVIEWER: (),
    Role.IMPLEMENTER: ("registry.npmjs.org",),
    Role.RESOLVER: ("registry.npmjs.org",),
    Role.VERIFIER: ("registry.npmjs.org",),
}


def _abs(p: Path) -> str:
    """Permission-rule absolute path syntax (``//`` anchors at the filesystem root)."""
    return "/" + str(p.resolve())


@dataclass(frozen=True)
class StageProfile:
    role: Role
    tools: tuple[str, ...]
    settings: dict[str, Any]
    add_dirs: tuple[Path, ...]
    writable: tuple[Path, ...]
    notes: tuple[str, ...] = field(default_factory=tuple)
    permission_mode: str = "dontAsk"


def build_profile(
    role: Role,
    *,
    worktree: Path,
    output_dir: Path,
    inputs_dir: Path,
    tmp_dir: Path,
    readonly_dirs: tuple[Path, ...] = (),
    network_domains: tuple[str, ...] | None = None,
) -> StageProfile:
    file_tools = ("Read", "Grep", "Glob", "Edit", "Write")
    bash = role in (Role.IMPLEMENTER, Role.RESOLVER, Role.VERIFIER)
    tools = (*file_tools, "Bash") if bash else file_tools
    allow = [f"Edit({_abs(output_dir)}/**)", f"Read({_abs(inputs_dir)}/**)"]
    if role is Role.RESOLVER:
        # The one tool that talks to the person in the session (resolution needs a developer).
        tools = (*tools, "AskUserQuestion")
        allow.append("AskUserQuestion")
    deny: list[str] = [f"Edit({_abs(d)}/**)" for d in (inputs_dir, *readonly_dirs)]
    if role in (Role.IMPLEMENTER, Role.RESOLVER):
        allow.append(f"Edit({_abs(worktree)}/**)")
        deny.extend(f"Edit({_abs(worktree)}/{p})" for p in PROTECTED_WORKTREE_PATHS)
    elif role is Role.VERIFIER:
        # No allow rule, so dontAsk denies file-tool edits to the worktree. An explicit deny
        # would also become a sandbox write ban and stop tests writing node_modules/dist; the
        # coordinator instead rejects any change to tracked files after the run.
        deny.extend(f"Edit({_abs(worktree)}/{p})" for p in PROTECTED_WORKTREE_PATHS)
    else:
        deny.append(f"Edit({_abs(worktree)}/**)")
    for path in CREDENTIAL_PATHS:
        deny.append(f"Read({path})")
        deny.append(f"Read({path}/**)")
    if bash:
        deny.extend(f"Bash({cmd} *)" for cmd in DENIED_COMMANDS)
        deny.extend(f"Bash({cmd})" for cmd in DENIED_COMMANDS)
    deny.extend(["WebFetch", "WebSearch", "mcp__*"])

    # AskUserQuestion is denied under dontAsk even when an allow rule names it (checked against
    # Claude Code 2.1.289), and the resolver needs it. A resolution only runs with the developer at
    # the keyboard, so anything outside the allow rules asks them instead of being denied. Deny
    # rules, --restricted and the OS sandbox are unchanged.
    mode = "default" if role is Role.RESOLVER else "dontAsk"
    domains = DEFAULT_NETWORK[role] if network_domains is None else network_domains
    settings: dict[str, Any] = {
        "permissions": {
            "allow": allow,
            "deny": deny,
            "defaultMode": mode,
            "disableBypassPermissionsMode": "disable",
        },
        "enableAllProjectMcpServers": False,
        "sandbox": {
            "enabled": True,
            "failIfUnavailable": True,
            "allowUnsandboxedCommands": False,
            "autoAllowBashIfSandboxed": bash,
            "filesystem": {
                "denyRead": list(CREDENTIAL_PATHS),
                "allowWrite": [str(output_dir), str(tmp_dir)],
            },
            "network": {
                "allowedDomains": list(domains),
                # Tests may start the app on the run's allocated port (loopback needs no domain
                # entry). allowMachLookup is deliberately off: with Claude Code 2.1.278 it makes
                # every Bash call need approval under dontAsk, so browser e2e (which needs it on
                # macOS) runs in the coordinator's own checks instead.
                "allowLocalBinding": bash,
            },
        },
    }
    writes_worktree = role in (Role.IMPLEMENTER, Role.RESOLVER)
    writable = (output_dir, tmp_dir) + ((worktree,) if writes_worktree else ())
    notes = (
        "worktree is read-only to file tools"
        if not writes_worktree
        else "protected paths denied: " + ", ".join(PROTECTED_WORKTREE_PATHS),
    )
    add_dirs = (output_dir, inputs_dir, *readonly_dirs)
    return StageProfile(role, tools, settings, add_dirs, writable, notes, mode)
